version: '3.1'

services:
  mongo:
    image: 'bitnami/mongodb:latest'
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGODB_ADVERTISED_HOSTNAME: 127.0.0.1
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: mongodb
      MONGODB_ROOT_PASSWORD: mongodb
      MONGODB_REPLICA_SET_KEY: mongodbreplicasetkey
      MONGODB_DATABASE: benchmark
