env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  prettier/prettier: 0
  no-param-reassign: 0
  no-return-assign: [2, except-parens]
