env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  prettier/prettier: off
  no-param-reassign: off
  no-console: off
