root: true
parser: '@typescript-eslint/parser'
env:
  es6: true
  node: true
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  prettier/prettier: 0
  no-param-reassign: 0
  no-return-assign: [2, except-parens]
