trailingComma: 'none'
tabWidth: 2
semi: true
singleQuote: true
printWidth: 100
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder: ["^[./]"]
importOrderSeparation: true
importOrderSortSpecifiers: true
