# Author: Hudson S. Borges
name: CI

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"
      - "Dockerfile"
      - "biome.json"
      - "tsconfig.json"
      - "vitest.config.ts"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"
      - "Dockerfile"
      - "biome.json"
      - "tsconfig.json"
      - "vitest.config.ts"
  workflow_dispatch:

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  build:
    name: Build source code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: corepack enable
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build source code
        run: yarn build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
